
THIS_PATH=/root/env/AUM-Ono-OS-Code-Environment
THIS_BUILD=$(THIS_PATH)/Build
BUILD_RESULTS=$(THIS_BUILD)/Result
THIS_OS = $(BUILD_RESULTS)/AUM-Ono-OS.bin


qemuRunOS:
	qemu-system-i386 -fda $(THIS_OS)
